### ISSUE TITLE
[Issue] Glitched Models and Animations

### ISSUE THREAD

**Issue by JohnnyEngland** [AdvancedPlugins/AdvancedMobs#104]
### Describe the bug

Recently i bought a both plugins AM and AP, and i'm struggling with so much glitches, i was expecting plugin without any bugs or something but, right now i wanna a refund, but i can't get bcs "I downloaded plugin" that's fucked. I'm using newest version of AdvancedMobs and AdvancedPets
Caused by: java.lang.NullPointerException: Cannot invoke "net.advancedplugins.mobs.impl.customMobs.entityInstance.CustomEntityInstance.setAsDisplay(org.bukkit.Location)" because the return value of "net.advancedplugins.mobs.impl.customMobs.CustomEntityHandler.spawnEntity(org.bukkit.Location, String)" is null
	at net.advancedplugins.mobs.handlers.commands.sub.DisplayMobSub.onExecute(DisplayMobSub.java:32) ~[AdvancedMobs-1.10.0.jar:?]
	at net.advancedplugins.mobs.impl.utils.commands.Command.middleMan(Command.java:28) ~[AdvancedMobs-1.10.0.jar:?]
	at net.advancedplugins.mobs.impl.utils.commands.CommandBase.onCommand(CommandBase.java:98) ~[AdvancedMobs-1.10.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]

### How to reproduce

Spawn an otter and there is silverfish not model that's was on screenshots on spigot. Use /am display otter and there is an error. 

### Screenshots / Videos

![Zrzut ekranu 2024-07-19 123200](https://github.com/user-attachments/assets/3d0975a6-403d-4e4c-be12-2e06efc88511)
![Zrzut ekranu 2024-07-19 123221](https://github.com/user-attachments/assets/0673dc39-e495-4ae3-b974-debc6640b1f7)
![Zrzut ekranu 2024-07-19 123324](https://github.com/user-attachments/assets/be039e28-41a8-494c-bd5a-2e50285d27b3)

### Server Log

https://mcpaste.io/58cbe1fae522c6d1

**Comment by JohnnyEngland** [comment]
That's how this shit is looking.
https://streamable.com/9l4dda
