### ISSUE TITLE
Task #711 for AdvancedMobs v1.0.5 generated an exception [Issue] 

### ISSUE THREAD

**Issue by MODNMETL** [AdvancedPlugins/AdvancedMobs#12]
### Describe the bug

Console error being thrown on server start (albeit we are running AdvancedMobs v1.0.6 it still cited v1.0.5 in the error:

[21:28:01 WARN]: [AdvancedMobs] Task #711 for AdvancedMobs v1.0.5 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState cannot be cast to class org.bukkit.block.CreatureSpawner (org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState and org.bukkit.block.CreatureSpawner are in unnamed module of loader java.net.URLClassLoader @18769467)
        at net.advancedplugins.mobs.handlers.spawners.AdvancedSpawner.setAsCustom(AdvancedSpawner.java:123) ~[AdvancedMobs-1.0.6.jar:?]
        at net.advancedplugins.mobs.handlers.spawners.AdvancedSpawner.<init>(AdvancedSpawner.java:37) ~[AdvancedMobs-1.0.6.jar:?]
        at net.advancedplugins.mobs.handlers.spawners.AdvancedSpawner.loadFromString(AdvancedSpawner.java:143) ~[AdvancedMobs-1.0.6.jar:?]
        at net.advancedplugins.mobs.handlers.spawners.SpawnersHandler.lambda$loadSpawners$1(SpawnersHandler.java:117) ~[AdvancedMobs-1.0.6.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.advancedplugins.mobs.handlers.spawners.SpawnersHandler.lambda$loadSpawners$2(SpawnersHandler.java:117) ~[AdvancedMobs-1.0.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1114) ~[paper-1.19.2.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Minecraft Paper 1.19.2 and AdvancedMobs plugin v1.0.5 or v1.0.6 (the error gets thrown on both of these versions)

### Server Log

https://mcpaste.io/e69579b0acfba325

**Comment by GC-spigot** [comment]
Fixed!
