### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by VisionHikooo** [AdvancedPlugins/AdvancedMobs#2]
The Plugin throws this exception in my console

java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.fromMobSpawner()'
        at net.advancedplugins.mobs.handlers.randomSpawning.RandomSpawnHandler.lambda$scanSpawns$0(RandomSpawnHandler.java:73) ~[?:?]

please help

**Comment by GC-spigot** [comment]
Can you post the full error please? I will tix this asap!On 2022-11-08, at 10:09 PM, VisionHikooo ***@***.***> wrote:﻿
The Plugin throws this exception in my console
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.fromMobSpawner()'
at net.advancedplugins.mobs.handlers.randomSpawning.RandomSpawnHandler.lambda$scanSpawns$0(RandomSpawnHandler.java:73) ~[?:?]
please help
