### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by choyatv** [AdvancedPlugins/AdvancedMobs#27]
### Describe the bug

Summoning and killing premium mobs causes a bug as the sound repeats.

mobs : Bear, Mammoth, AdvancedMobsOtte, deer, 

### How to reproduce

[
[23:53:36] [Server thread/INFO]: Choya_TV issued server command: /gamemode spectator
[23:53:38] [Server thread/INFO]: Choya_TV issued server command: /gamemode creative
[23:54:16] [Server thread/INFO]: Choya_TV issued server command: /advancedmobs mob bear
[23:54:18] [Server thread/ERROR]: Could not pass event CustomEntityPunchEvent to AdvancedMobs v1.2.4
java.lang.NoSuchMethodError: 'com.ticxo.modelengine.api.animation.AnimationProperty com.ticxo.modelengine.api.animation.AnimationHandler.getAnimation(java.lang.String)'
	at net.advancedplugins.mobs.impl.customMobs.entityInstance.ModelEngineEntityInstance.tryRemovingModel(ModelEngineEntityInstance.java:63) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at net.advancedplugins.mobs.impl.customMobs.entityInstance.ModelEngineEntityInstance.kill(ModelEngineEntityInstance.java:57) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at net.advancedplugins.mobs.listeners.MobDeathListener.handleDeath(MobDeathListener.java:106) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at net.advancedplugins.mobs.listeners.MobDeathListener.onCustomPunch(MobDeathListener.java:40) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor475.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-383]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.advancedplugins.mobs.impl.customMobs.listeners.CustomEntityPunchListener.onDamage(CustomEntityPunchListener.java:53) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor461.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-383]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[paper-1.19.3.jar:git-Paper-383]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1154) ~[paper-1.19.3.jar:git-Paper-383]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1013) ~[paper-1.19.3.jar:git-Paper-383]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:965) ~[paper-1.19.3.jar:git-Paper-383]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1188) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2150) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1385) ~[?:?]
	at net.minecraft.world.entity.monster.Silverfish.hurt(Silverfish.java:105) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1314) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2118) ~[?:?]
	at com.ticxo.modelengine.nms.v1_19_R2.network.interact.PatchedInteractHandler$1.a(PatchedInteractHandler.java:150) ~[Model-Engine-R3.1.3.jar:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at com.ticxo.modelengine.nms.v1_19_R2.network.interact.ServerboundInteractPacketWrapper.a(ServerboundInteractPacketWrapper.java:46) ~[Model-Engine-R3.1.3.jar:?]
	at com.ticxo.modelengine.nms.v1_19_R2.network.interact.PatchedInteractHandler.handleInteract(PatchedInteractHandler.java:91) ~[Model-Engine-R3.1.3.jar:?]
	at com.ticxo.modelengine.nms.v1_19_R2.network.interact.ServerboundInteractPacketWrapper.a(ServerboundInteractPacketWrapper.java:30) ~[Model-Engine-R3.1.3.jar:?]
	at com.ticxo.modelengine.nms.v1_19_R2.network.interact.ServerboundInteractPacketWrapper.a(ServerboundInteractPacketWrapper.java:11) ~[Model-Engine-R3.1.3.jar:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-383]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:54:18] [Server thread/WARN]: [AdvancedMobs] Task #89 for AdvancedMobs v1.2.4 generated an exception
java.lang.NoSuchMethodError: 'com.ticxo.modelengine.api.animation.AnimationProperty com.ticxo.modelengine.api.animation.AnimationHandler.getAnimation(java.lang.String)'
	at net.advancedplugins.mobs.impl.customMobs.entityInstance.ModelEngineEntityInstance.tryRemovingModel(ModelEngineEntityInstance.java:63) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at net.advancedplugins.mobs.impl.customMobs.entityInstance.ModelEngineEntityInstance.kill(ModelEngineEntityInstance.java:57) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at net.advancedplugins.mobs.impl.customMobs.CustomEntityHandler$1.run(CustomEntityHandler.java:198) ~[AdvancedMobs-1.2.4 (1).jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-383]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-383]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-383]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by GC-spigot** [comment]
What version of ModelEngine do you have? Only 3.0.0+ is supported
