### ISSUE TITLE
AdvancedMobs despawning after server restarts

### ISSUE THREAD

**Issue by Zero-Escape** [AdvancedPlugins/AdvancedMobs#35]
Hello, I use a couple advanced plugins on my server but Im having an issue where the custom mobs spawned in using advancedmobs are despawning after server restarts.
I have 57 active plugins on my server so it is possible there is a conflict of some kind. Here are couple things worth noting.
- I have made sure that the persistent mobs is set to true in the config file
- I have random spawning disabled, and am instead using exclusively spawn eggs from the plugin that are shared using a rewards crate system. (let me know if you need specifics of this)
- The mobs work perfectly and do NOT despawn if players leave the area/chunk or even if players are only active in another world (multiverse)
They only despawn when the server restarts
here is the code from my config.yml:
`# AdvancedMobs by GC
# Version: 1.2.8
# Release date: 17/02/2023

# Wiki: https://mobs.advancedplugins.net

settings:
  language: en

# Custom Mob Spawners
customMobSpawners:
  disabled: false # if set to true, any spawner handling will be disabled and custom mob spawners will not work

# Spawner Stacking Settings
spawnerStacking:
  # Is spawner stacking enabled?
  enabled: false
  # Maximum number of spawners in a stack
  maxSpawnersPerStack: 100
  # Max distance in which spawners will stack together
  maxStackDistance: 5
  # Number of net.advancedplugins.mobs spawning per spawner
  mobsPerSpawner: "<random>1-4</random> * %spawner count% * %upgrades%"
  # Default spawner spawning speed, in ticks
  spawnSpeed: 600

# Stacked spawner breaking configuration
spawnerBreaking:
  silktouch:
    # Is silk touch required to break a spawner?
    required: true
    # Silk touch permission required to break spawners
    # Set as '' to disable
    permission: 'advancedmobs.silktouch'
  # Should all stacked spawners be broken at once?
  breakAll: false
  # Should spawners be teleported to inventory instead of dropping?
  teleportToInv: true
  # Chance for spawners to drop from explosion.
  # Set as 0 to disable
  dropFromExplosionChance: 20

# Mob Stacking Configuration
mobStacking:
  # Is mob stacking enabled?
  enabled: false
  # Should vanilla net.advancedplugins.mobs stack?
  # If set to false, only custom net.advancedplugins.mobs will stack
  stackVanillaMobs: true
  # Max distance in which net.advancedplugins.mobs will stack together
  maxMobStackDistance: 16
  # Maximum number of net.advancedplugins.mobs in a stack
  maxMobsPerStack: 100
  # Should whole stack die when one is killed?
  wholeStackDeath: false
  # Stacked Mobs Blacklist
  # Add any mob type you want here to not stack
  mobBlacklist:
    - 'ENDER_DRAGON'
  # Should mobBlacklist work as whitelist?
  # If set to true, only net.advancedplugins.mobs from this list will stack
  mobBlacklistAsWhitelist: false
  # Should net.advancedplugins.mobs from spawners have AI?
  # If set to false, net.advancedplugins.mobs from spawners will not have AI - will not walk or attack.
  spawnerMobsAI: true

# Custom Mobs Settings
customMobs:
  # Should mob turn red when it's damaged?
  #  An artificial "damaged" animation is played for custom net.advancedplugins.mobs upon damage
  #  Setting to false will only show particles
  customDamageAnimation: true

  # Should custom net.advancedplugins.mobs be persistent? If enabled, they will act like vanilla net.advancedplugins.mobs and
  #  custom net.advancedplugins.mobs won't disappear after restarts or when leaving areas.
  #  If set to false, once area is left or server restarts, net.advancedplugins.mobs will not respawn
  persistentMobs: true

  # Limit of custom net.advancedplugins.mobs in 1 chunk
  #  Maximum is 50 net.advancedplugins.mobs per chunk
  customMobsPerChunk: 16
`

**Comment by Zero-Escape** [comment]
Here is the warnings I get when the server restarts and there is one custom mob spawned in the world. 
Upon server restart the mob is gone
```
02.03 18:46:25 [Server] INFO Enabling AdvancedMobs v1.3.0
02.03 18:46:25 [Server] INFO Loaded 36,570 custom heads
02.03 18:46:25 [Server] INFO Bear.amob model wasn't loaded - it requires ModelEngine: https://mobs.advancedplugins.net/supported-plugins/modelengine
02.03 18:46:25 [Server] INFO Mammoth.amob model wasn't loaded - it requires ModelEngine: https://mobs.advancedplugins.net/supported-plugins/modelengine
02.03 18:46:25 [Server] INFO Otter.amob model wasn't loaded - it requires ModelEngine: https://mobs.advancedplugins.net/supported-plugins/modelengine
02.03 18:46:25 [Server] INFO Reindeer.amob model wasn't loaded - it requires ModelEngine: https://mobs.advancedplugins.net/supported-plugins/modelengine
02.03 18:46:25 [Server] INFO Loaded 20 mob configurations.
02.03 18:46:25 [Server] INFO Loaded 7 breed-able Mobs
02.03 18:46:25 [Server] WARN java.lang.NullPointerException: Cannot invoke "net.advancedplugins.mobs.impl.customMobs.entityBuilders.subclass.ItemProperty.getItem()" because "<local2>" is null
02.03 18:46:25 [Server] WARN at AdvancedMobs-1.3.0.jar//net.advancedplugins.mobs.impl.customMobs.entityBuilders.EntityBase.getDisplayitem(EntityBase.java:330)
02.03 18:46:25 [Server] WARN at AdvancedMobs-1.3.0.jar//net.advancedplugins.mobs.handlers.discoveries.DiscoveriesHandler.loadHeads(DiscoveriesHandler.java:41)
02.03 18:46:25 [Server] WARN at AdvancedMobs-1.3.0.jar//net.advancedplugins.mobs.handlers.discoveries.DiscoveriesHandler.<init>(DiscoveriesHandler.java:33)
02.03 18:46:25 [Server] WARN at AdvancedMobs-1.3.0.jar//net.advancedplugins.mobs.Core.onEnable(Core.java:319)
02.03 18:46:25 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
02.03 18:46:25 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
02.03 18:46:25 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
02.03 18:46:25 [Server] WARN at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
02.03 18:46:25 [Server] WARN at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
02.03 18:46:25 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
02.03 18:46:25 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
02.03 18:46:25 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
02.03 18:46:25 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
02.03 18:46:25 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
02.03 18:46:25 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
02.03 18:46:25 [Server] WARN Failed to load head for WITHER SKELETON mob.
02.03 18:46:25 [Server] WARN Failed to load head for ZOMBIE VILLAGER mob.
02.03 18:46:25 [Server] WARN Failed to load head for ENDER DRAGON mob.
02.03 18:46:25 [Server] WARN Failed to load head for MUSHROOM COW mob.
02.03 18:46:25 [Server] WARN Failed to load head for TROPICAL FISH mob.
02.03 18:46:25 [Server] WARN Failed to load head for TRADER LLAMA mob.
02.03 18:46:25 [Server] WARN Loaded 93 mob heads
```

**Comment by Zero-Escape** [comment]
Here is my full log

https://paste.shockbyte.com/wirehakiqugiyufuyowo

**Comment by finder1793** [comment]
I have encountered that error as well
