### ISSUE TITLE
[Issue] NoSuchMethodError with AM(v1.8.10), Premium-Mobs-Pack & ModelEngine4

### ISSUE THREAD

**Issue by Mitality** [AdvancedPlugins/AdvancedMobs#80]
### Describe the bug

Attempts to summon a "premium mob" (bear, reindeer, mammoth) couse a NoSuchMethodError with the newest version of ModelEngine4 (ModelEngine3 works, but that's besides the point)

(Using ModelEngine3 instead of ModelEngine4 most certainly isn't an option, since ModelEngine4 features are used for other things and installing both versions at the same time would probably cause even more problems...)

ERROR LOG:
org.bukkit.command.CommandException: Unhandled exception executing command 'amobs' in plugin AdvancedMobs v1.8.10
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-389]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-389]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2236) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2196) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1452) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1352) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-389]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.ticxo.modelengine.api.model.ModeledEntity.addModel(com.ticxo.modelengine.api.model.ActiveModel, boolean)'
        at net.advancedplugins.mobs.impl.customMobs.entityInstance.ModelEngineEntityInstance.spawn(ModelEngineEntityInstance.java:46) ~[AdvancedMobs-1.8.10.jar:?]
        at net.advancedplugins.mobs.impl.customMobs.CustomEntityHandler.spawnEntity(CustomEntityHandler.java:352) ~[AdvancedMobs-1.8.10.jar:?]
        at net.advancedplugins.mobs.impl.customMobs.CustomEntityHandler.spawnEntity(CustomEntityHandler.java:327) ~[AdvancedMobs-1.8.10.jar:?]
        at net.advancedplugins.mobs.impl.customMobs.CustomEntityHandler.spawnEntity(CustomEntityHandler.java:342) ~[AdvancedMobs-1.8.10.jar:?]
        at net.advancedplugins.mobs.handlers.commands.sub.SpawnMobSub.onExecute(SpawnMobSub.java:31) ~[AdvancedMobs-1.8.10.jar:?]
        at net.advancedplugins.mobs.impl.utils.commands.Command.middleMan(Command.java:28) ~[AdvancedMobs-1.8.10.jar:?]
        at net.advancedplugins.mobs.impl.utils.commands.CommandBase.onCommand(CommandBase.java:97) ~[AdvancedMobs-1.8.10.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

### How to reproduce

Install AdvancedMobs v1.8.10 (https://advancedplugins.net/item/AdvancedMobs.47/) and ModelEngine4 (https://mythiccraft.io/index.php?pages/official-modelengine4-download/) on Mc 1.20.4 (Paper), Download the Premium-Mobs-Pack (https://advancedplugins.net/item/Premium-Mobs-Pack.80), provide the files to ModelEngine and use the generated ressourcepack, then try to summon a "premium mob" with AdvancedMobs (For example: "/am mob bear").

**Comment by GC-spigot** [comment]
Model engine 4 is not yet supported

**Comment by Mitality** [comment]
Alr, that's sad... Are there any plans to change this in the near future?
